[package]
name = "jerry-render"
version = "0.1.0"
edition = "2021"
description = "A simple toy web rendering engine"
authors = ["Jerry Web Labs"]

[dependencies]
image = "0.24"

[[bin]]
name = "jerry-render"
path = "main.rs"
